---

# **IT Training Assignment Class 4**

---

### **Import Required Libraries**

In [78]:
import numpy as np
import cv2

### **Task 01: 1D & 2D Array Operations**

In [79]:
# Create a 1D and 2D array (Global Variables)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [80]:
# Output the arrays
print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
# Implement a function for Basic array Operations
def basic_array_operations():
  # 1D array operations
  print("Sum of 1D Array:", np.sum(array_1d))

  # 2D array operations
  print("Mean of a 2D Array::", np.mean(array_2d))
  print("Transpose of 2D Array:\n",array_2d.T)


In [82]:
# Create global array variables
global arr_1d;
global arr_2d;

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Call basic array operations function
basic_array_operations()

Sum of 1D Array: 15
Mean of a 2D Array:: 5.0
Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


### **Task 02: Image Processing with NumPy**

In [83]:
# Implement a function to create and crop the image using local variables
def image_processing():
  # Create a grayscale image using 2d numpy array
  image = np.random.randint(0, 256, (5, 5), dtype=np.uint8)

  # Print original Image
  print("Original Image:\n", image)

  # Crop the image
  cropped = image[1:4, 1:4]
  # Invert colors
  inverted_image = 255 - image

  # Print cropped section of image
  print("Cropped Section:\n", cropped)
  # Print inverted image
  print("Inverted Image:\n", inverted_image)

In [84]:
# Call the image processing function to print output
image_processing()

Original Image:
 [[254  76  29  74  29]
 [ 16 232 183   6 118]
 [133 156  20  51  68]
 [144 137  46   1 105]
 [ 72  84 179  33  73]]
Cropped Section:
 [[232 183   6]
 [156  20  51]
 [137  46   1]]
Inverted Image:
 [[  1 179 226 181 226]
 [239  23  72 249 137]
 [122  99 235 204 187]
 [111 118 209 254 150]
 [183 171  76 222 182]]


### **Task 03: Augmented Reality Transformation: Perform linear algebra operations like scaling, rotation, and translation.**

In [91]:
image_path = "D:\JAPANESE-IT-PROGRAM\Class 4\my_image.jpg"  # Adjust this
image = cv2.imread(image_path)


<>:1: SyntaxWarning: invalid escape sequence '\J'
<>:1: SyntaxWarning: invalid escape sequence '\J'
C:\Users\Ausaf\AppData\Local\Temp\ipykernel_12380\1667624457.py:1: SyntaxWarning: invalid escape sequence '\J'
  image_path = "D:\JAPANESE-IT-PROGRAM\Class 4\my_image.jpg"  # Adjust this


In [86]:
# Implement a function to scale image by a scale factor
def scale_image(image, scale_factor):
  # Create a scale matrix from scale factor

  scaling_matrix = np.array([[scale_factor, 0, 0],
                             [0, scale_factor, 0],
                             [0, 0, 1]])
  # Get image dimensions
  rows, cols = image.shape[:2]

  # Apply transformation and return scaled image
  scaled_image = cv2.warpPerspective(image, scaling_matrix, (cols, rows))
  return scaled_image

In [87]:
# Implement a function to rotate and image by a given angle
def rotate_image(image, angle):
  # Get image dimensions
  rows, cols = image.shape[:2]

  # Calculate rotation matrix
  rotation_matrix = cv2.getRotationMatrix2D((cols/2, rows/2), angle, 1)

  # Apply rotation and return the rotated image
  rotated_image = cv2.warpAffine(image, rotation_matrix, (cols, rows))
  return rotated_image

In [88]:
# Implement a function to translate an image to x, y axis
def translate_image(image, tx, ty):
  # Create translation matrix
  translation_matrix = np.array([[1, 0, tx],
                                 [0, 1, ty]], dtype=np.float32)
  # Get image dimensions
  rows, cols = image.shape[:2]

  # Apply transformation
  translated_image = cv2.warpAffine(image, translation_matrix, (cols, rows))
  return translated_image

In [89]:
import cv2

# Load the image
image = cv2.imread("your_image.jpg")

if image is None:
    raise ValueError("Error: Unable to load the image. Check the file path!")

# Apply transformations
scaled_image = scale_image(image, 1.5)
rotated_image = rotate_image(image, 45)
translated_image = translate_image(image, 50, 30)

# Display images
cv2.imshow("Original Image", image)
cv2.imshow("Scaled Image", scaled_image)
cv2.imshow("Rotated Image", rotated_image)
cv2.imshow("Translated Image", translated_image)

# Wait for key press and close windows
cv2.waitKey(0)
cv2.destroyAllWindows()


ValueError: Error: Unable to load the image. Check the file path!

### **Task 04: Face Detection from Image Arrays – Extract facial features by slicing a NumPy-based image array.**

In [ ]:
# Preprocess Image to grayscale
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [ ]:
# Load OpenCV's pretrained Haar Cascade for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [ ]:
# Detect face in image
faces = face_cascade.detectMultiScale(image_gray, scaleFactor=1.1, minNeighbors=5)

In [ ]:
# Loop through detected faces and extracted facial features
for (x, y, w, h) in faces:
  # Extract facial features
  face_roi = image_gray[y:y+h, x:x+w]

  # Display face region
  cv2_imshow(face_roi)

  # Extract additional features
  eyes_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
  eyes = eyes_cascade.detectMultiScale(face_roi, scaleFactor=1.1, minNeighbors=5)

  # Display eye regions
  for (ex, ey, ew, eh) in eyes:
    eye_roi = face_roi[ey:ey+eh, ex:ex+ew]
    cv2_imshow(eye_roi)

# Show original image with detected face
print("Detected Face")
cv2_imshow(image)

cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'faces' is not defined

---